/* TinyMLC - Tiny Machine Learning Compiler
 *
 * Copyright (c) 2026 Jia Liu & TinyMLC Contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * This file is part of TinyMLC.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Auto-generated code, do not modify manually
// Generated by tinymlc

#ifndef TINYMLC_MODEL_H
#define TINYMLC_MODEL_H

#include <stdint.h>

#define INPUT_SIZE {{ input_size }}
#define OUTPUT_SIZE {{ output_size }}

{% if inputs_count >= 1 %}
#define INPUT_SIZE_1 {{ INPUT_SIZE_1 }}
{% endif %}
{% if inputs_count >= 2 %}
#define INPUT_SIZE_2 {{ INPUT_SIZE_2 }}
{% endif %}

{% if target == "arm" %}
// FC quantization parameters
#define FC_INPUT_OFFSET 0
#define FC_OUTPUT_OFFSET 0
#define FC_MULTIPLIER {{ fc_multiplier }}
#define FC_SHIFT {{ fc_shift }}

// Softmax quantization parameters
#define SOFTMAX_MULTIPLIER {{ softmax_multiplier }}
#define SOFTMAX_SHIFT {{ softmax_shift }}
#define SOFTMAX_DIFF_MIN -128
{% endif %}

// LSTM right shift bits (calculated from model quantization parameters)
#define LSTM_SHIFT_I {{ lstm_shifts[0] }}
#define LSTM_SHIFT_F {{ lstm_shifts[1] }}
#define LSTM_SHIFT_G {{ lstm_shifts[2] }}
#define LSTM_SHIFT_O {{ lstm_shifts[3] }}

// Inference function declaration
{% if inputs_count == 1 %}
    void {{ inference_func }}(const int8_t* input, int8_t* output);
{% elif inputs_count == 2 %}
    void {{ inference_func }}(const int8_t* input1,
                              const int8_t* input2,
                              int8_t* output);
{% endif %}

#endif // TINYMLC_MODEL_H
