// Auto-generated code, do not modify manually
// Generated by tinymlc

#include "tinymlc.h"
{{ includes }}
#include "model.h"
#include "debug_print.h"
#include <stddef.h>

// Input/output sizes
#define INPUT_SIZE {{ input_size }}
#define OUTPUT_SIZE {{ output_size }}

// Intermediate tensor memory (static allocation, placed outside function)
{% for tensor in tensors_to_define %}
{{ tensor.type }} tensor_{{ tensor.index }}[{{ tensor.size }}] __attribute__((section(".bss")));
{% endfor %}

{% if has_lstm %}
// LSTM parameters
#define LSTM_TIME_STEPS {{ lstm_time_steps }}
#define LSTM_HIDDEN_SIZE {{ lstm_hidden_size }}
#define TINYMLC_HAS_LSTM
{% endif %}

// Inference function
{% if inputs_count == 1 %}
void {{ inference_func }}(const int8_t* input, int8_t* output) {
    // Input tensor mapping
    int8_t* tensor_{{ input_tensor_indices[0] }} = (int8_t*)input;
{% elif inputs_count == 2 %}
void {{ inference_func }}(const int8_t* input1, const int8_t* input2, int8_t* output) {
    // Input tensor mapping
    int8_t* tensor_{{ input_tensor_indices[0] }} = (int8_t*)input1;
    int8_t* tensor_{{ input_tensor_indices[1] }} = (int8_t*)input2;
{% endif %}
    // Execute operators in order
    {% for op in execution_order %}
        {% if op.op_name == "UNIDIRECTIONAL_SEQUENCE_LSTM" %}
        tmlc_unidirectional_sequence_lstm_s8(
            tensor_{{ op.input_indices[0] }},
            lstm_input_weights,
            lstm_recurrent_weights,
            lstm_bias,
            tensor_{{ op.output_indices[0] }},
            NULL, NULL,
            {{ op.lstm_params.time_steps }},
            {{ op.lstm_params.batch_size }},
            {{ op.lstm_params.input_size }},
            {{ op.lstm_params.hidden_size }}
        );
        {% elif op.op_name == "FULLY_CONNECTED" %}
        tmlc_fully_connected_s8(
            tensor_{{ op.input_indices[0] }},
            fc_weights,
            fc_bias,
            tensor_{{ op.output_indices[0] }},
            {{ tensor_sizes[op.input_indices[0]] }},
            {{ tensor_sizes[op.output_indices[0]] }},
            {{ fc_multiplier }},
            {{ fc_shift }}
        );
        {% elif op.op_name == "SOFTMAX" %}
        tmlc_softmax_s8(
            tensor_{{ op.input_indices[0] }},
            tensor_{{ op.output_indices[0] }},
            {{ tensor_sizes[op.input_indices[0]] }}
        );
        {% elif op.op_name == "RESHAPE" %}
        {
            static const int reshape_target[] = { {% for s in op.reshape_target_shape %}{{ s }}{% if not loop.last %}, {% endif %}{% endfor %} };
            int reshape_input_size = {{ tensor_sizes[op.input_indices[0]] }};
            tmlc_reshape_s8(
                tensor_{{ op.input_indices[0] }},
                tensor_{{ op.output_indices[0] }},
                reshape_input_size,
                reshape_target,
                {{ op.reshape_target_shape | length }}
            );
        }
        {% elif op.op_name == "ADD" %}
        tmlc_add_s8(
            tensor_{{ op.input_indices[0] }},
            tensor_{{ op.input_indices[1] }},
            tensor_{{ op.output_indices[0] }},
            {{ tensor_sizes[op.output_indices[0]] }}
        );
        {% elif op.op_name == "SVDF" %}
        tmlc_svdf_s8(
            tensor_{{ op.data_input_idx }},
            svdf_weights,
            svdf_bias,
            tensor_{{ op.output_indices[0] }},
            {{ op.svdf_params.time_steps }},
            {{ op.svdf_params.input_size }},
            {{ op.svdf_params.rank }},
            {{ op.svdf_params.units }}
        );
        {% elif op.op_name == "CONV_2D" %}
        tmlc_conv2d_s8(
            tensor_{{ op.data_input_idx }},
            conv_weights,
            conv_bias,
            tensor_{{ op.output_indices[0] }},
            {{ op.conv_params.input_h }},
            {{ op.conv_params.input_w }},
            {{ op.conv_params.input_c }},
            {{ op.conv_params.output_h }},
            {{ op.conv_params.output_w }},
            {{ op.conv_params.output_c }},
            {{ op.conv_params.kernel_h }},
            {{ op.conv_params.kernel_w }},
            {{ op.conv_params.stride_h }},
            {{ op.conv_params.stride_w }},
            {{ op.conv_params.padding_h }},
            {{ op.conv_params.padding_w }},
            {{ conv_multiplier }},
            {{ conv_shift }}
        );
        {% elif op.op_name == "MAX_POOL_2D" %}
        tmlc_max_pool_2d_s8(
            tensor_{{ op.data_input_idx }},
            tensor_{{ op.output_indices[0] }},
            {{ op.pool_params.input_h }},
            {{ op.pool_params.input_w }},
            {{ op.pool_params.input_c }},
            {{ op.pool_params.output_h }},
            {{ op.pool_params.output_w }},
            {{ op.pool_params.output_c }},
            {{ op.pool_params.pool_size_h }},
            {{ op.pool_params.pool_size_w }},
            {{ op.pool_params.stride_h }},
            {{ op.pool_params.stride_w }},
            0, 0
        );
        {% elif op.op_name == "DEPTHWISE_CONV_2D" %}
        tmlc_depthwise_conv_2d_s8(
            tensor_{{ op.data_input_idx }},
            dw_weights,
            dw_bias,
            tensor_{{ op.output_indices[0] }},
            {{ op.dw_params.input_h }},
            {{ op.dw_params.input_w }},
            {{ op.dw_params.input_c }},
            {{ op.dw_params.output_h }},
            {{ op.dw_params.output_w }},
            {{ op.dw_params.output_c }},
            {{ op.dw_params.kernel_h }},
            {{ op.dw_params.kernel_w }},
            1, 1,
            {{ op.dw_params.depth_multiplier }},
            0, 0
        );
        {% elif op.op_name == "RELU" %}
        tmlc_relu_s8(
            tensor_{{ op.input_indices[0] }},
            tensor_{{ op.output_indices[0] }},
            {{ tensor_sizes[op.input_indices[0]] }}
        );
        {% elif op.op_name == "AVERAGE_POOL_2D" %}
        tmlc_avg_pool_2d_s8(
            tensor_{{ op.data_input_idx }},
            tensor_{{ op.output_indices[0] }},
            {{ op.pool_params.input_h }},
            {{ op.pool_params.input_w }},
            {{ op.pool_params.input_c }},
            {{ op.pool_params.output_h }},
            {{ op.pool_params.output_w }},
            {{ op.pool_params.output_c }},
            {{ op.pool_params.pool_h }},
            {{ op.pool_params.pool_w }},
            {{ op.pool_params.stride_h }},
            {{ op.pool_params.stride_w }},
            0, 0
        );
        {% elif op.op_name == "TRANSPOSE" %}
        tmlc_transpose_s8(
            tensor_{{ op.data_input_idx }},
            NULL,
            tensor_{{ op.output_indices[0] }},
            {{ op.transpose_params.input_dims }},
            (const int[]){ {% for s in tensor_shapes[op.data_input_idx] %}{{ s }}{% if not loop.last %}, {% endif %}{% endfor %} }
        );
        {% elif op.op_name == "PAD" %}
        tmlc_pad_s8(
            tensor_{{ op.data_input_idx }},
            NULL,  // paddings, currently NULL
            tensor_{{ op.output_indices[0] }},
            4,
            (const int[]){ {% for s in tensor_shapes[op.data_input_idx] %}{{ s }}{% if not loop.last %}, {% endif %}{% endfor %} },
            (const int[]){ {% for s in tensor_shapes[op.output_indices[0]] %}{{ s }}{% if not loop.last %}, {% endif %}{% endfor %} }
        );
        {% elif op.op_name == "MEAN" %}
        tmlc_mean_s8(
            tensor_{{ op.data_input_idx }},
            tensor_{{ op.output_indices[0] }},
            {{ op.mean_params.input_dims }},
            (const int[]){ {% for s in tensor_shapes[op.data_input_idx] %}{{ s }}{% if not loop.last %}, {% endif %}{% endfor %} },
            (const int[]){ {% for s in tensor_shapes[op.output_indices[0]] %}{{ s }}{% if not loop.last %}, {% endif %}{% endfor %} },
            NULL,
            0,
            0
        );
        {% elif op.op_name == "MULTIPLY" %}
        tmlc_multiply_s8(
            tensor_{{ op.input_indices[0] }},
            tensor_{{ op.input_indices[1] }},
            tensor_{{ op.output_indices[0] }},
            {{ tensor_sizes[op.output_indices[0]] }}
        );
        {% elif op.op_name == "SIGMOID" %}
        tmlc_sigmoid_s8(
            tensor_{{ op.input_indices[0] }},
            tensor_{{ op.output_indices[0] }},
            {{ tensor_sizes[op.input_indices[0]] }}
        );
        {% elif op.op_name == "CONCAT" %}
        {
            static const int8_t* concat_inputs[] = { {% for idx in op.input_indices %}tensor_{{ idx }}{% if not loop.last %}, {% endif %}{% endfor %} };
            static const int concat_sizes[] = { {% for idx in op.input_indices %}{{ tensor_sizes[idx] }}{% if not loop.last %}, {% endif %}{% endfor %} };
            tmlc_concat_s8(
                concat_inputs,
                concat_sizes,
                {{ op.input_indices | length }},
                tensor_{{ op.output_indices[0] }}
            );
        }
        {% elif op.op_name == "SUB" %}
        tmlc_sub_s8(
            tensor_{{ op.input_indices[0] }},
            tensor_{{ op.input_indices[1] }},
            tensor_{{ op.output_indices[0] }},
            {{ tensor_sizes[op.output_indices[0]] }}
        );
        {% elif op.op_name == "TANH" %}
        tmlc_tanh_s8(
            tensor_{{ op.input_indices[0] }},
            tensor_{{ op.output_indices[0] }},
            {{ tensor_sizes[op.input_indices[0]] }}
        );
        {% endif %}
    {% endfor %}

    // Output tensor mapping
    if (output != NULL) {
        for (int i = 0; i < OUTPUT_SIZE; i++) {
            output[i] = tensor_{{ last_output_tensor }}[i];
        }
    }
}
