# table.py
# Table-driven network generation.
#
# The table contains pre-computed optimal network structures for
# different hardware constraints. This allows instant lookup without
# running the generate algorithm.
#
# Table operations:
#   - build_table: Generate a table from scratch
#   - lookup: Find the best network for given constraints
#   - update_table: Add new entries or recalibrate existing ones
#   - merge: Combine two tables
#   - prune: Remove stale entries
#   - get_stats: Get table statistics

import json
import copy
import hashlib
import time
from typing import Dict, Any, Optional, List, Tuple
from pathlib import Path
import numpy as np

from tinymlc.ANG.estimator import Estimator
from tinymlc.ANG.model_generator import ModelGenerator
from tinymlc.ANG.model_builder import ModelBuilder
from tinymlc.ANG.utils import (calculate_macs, calculate_params,
                               calculate_peak_ram)


class TableManager:
    """
    Manager for hardware profile tables.

    Tables map hardware constraints (MACs, RAM, Flash) to optimal
    network structures. They are generated by running the generate
    algorithm once and saving the results for instant reuse.
    """

    def __init__(self, table_path: Optional[str] = None):
        """
        Initialize the table manager.

        Args:
            table_path: Path to the table file (JSON).
                       If provided, the table is loaded immediately.
        """
        self.entries: List[Dict[str, Any]] = []
        self.metadata: Dict[str, Any] = {}
        self._index: Dict[str, int] = {}  # signature -> entry index
        self._table_path = table_path

        if table_path and Path(table_path).exists():
            self.load(table_path)

    def load(self, table_path: str) -> None:
        """
        Load a table from a JSON file.

        Args:
            table_path: Path to the table file.
        """
        with open(table_path, "r") as f:
            data = json.load(f)

        self.metadata = data.get("metadata", {})
        self.entries = data.get("entries", [])
        self._rebuild_index()

    def save(self, table_path: str) -> None:
        """
        Save the table to a JSON file.

        Args:
            table_path: Path to the output file.
        """
        data = {
            "version": self.metadata.get("version", "1.0"),
            "table_type": "hardware_profile",
            "metadata": self.metadata,
            "entries": self.entries,
        }

        with open(table_path, "w") as f:
            json.dump(data, f, indent=2, default=self._json_encoder)

        self._table_path = table_path

    def _json_encoder(self, obj: Any) -> Any:
        """
        Custom JSON encoder for numpy arrays.

        Args:
            obj: Object to encode.

        Returns:
            JSON-serializable representation.
        """
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        return str(obj)

    def _rebuild_index(self) -> None:
        """
        Rebuild the lookup index from entries.
        """
        self._index = {}
        for idx, entry in enumerate(self.entries):
            signature = entry.get("signature", "")
            if signature:
                self._index[signature] = idx

    def _get_signature(self, entry: Dict[str, Any]) -> str:
        """
        Generate a signature for a table entry.

        The signature is a unique identifier based on the layer sequence.

        Args:
            entry: Table entry.

        Returns:
            Signature string.
        """
        ops = entry.get("op_sequence", [])
        # Normalize to a string
        parts = []
        for op in ops:
            op_type = op.get("type", "unknown")
            # Include key parameters
            if op_type == "conv":
                parts.append(
                    f"conv_{op.get('kernel', 3)}x{op.get('kernel', 3)}_"
                    f"{op.get('cin', 0)}_c{op.get('cout', 0)}"
                    f"_s{op.get('stride', 1)}"
                )
            elif op_type == "pool":
                parts.append(
                    f"pool_{op.get('pool_type', 'max')}_"
                    f"{op.get('kernel', 2)}x{op.get('kernel', 2)}"
                    f"_s{op.get('stride', 2)}"
                )
            elif op_type == "fc":
                parts.append(
                    f"fc_{op.get('units', 0)}"
                )
            elif op_type == "add":
                parts.append(
                    f"add_{op.get('inputs', [])}"
                )
            else:
                parts.append(op_type)

        return "_".join(parts)

    def build_table(
        self,
        board: str,
        estimator: Estimator,
        num_entries: int = 100,
        max_layers: int = 10,
        input_shape: List[int] = None,
        num_classes: int = 10,
    ) -> None:
        """
        Build a hardware profile table from scratch.

        This runs the generate algorithm for different constraint
        combinations and saves the best network for each.

        Args:
            board: Board name (e.g., "stm32f4", "esp32s3").
            estimator: Estimator to use for evaluation.
            num_entries: Number of entries to generate.
            max_layers: Maximum layers in a network.
            input_shape: Input tensor shape.
            num_classes: Number of output classes.
        """
        if input_shape is None:
            input_shape = [1, 28, 28, 1]

        self.metadata = {
            "board": board,
            "estimator": estimator.get_info(),
            "generated_at": time.time(),
            "num_entries": num_entries,
            "max_layers": max_layers,
            "input_shape": input_shape,
            "num_classes": num_classes,
        }

        # Generate entries for different constraint levels
        # MACs ranges: 10k, 20k, 50k, 100k, 200k, 500k, 1M
        macs_ranges = [10000, 20000, 50000, 100000, 200000, 500000, 1000000]
        # RAM ranges: 8KB, 16KB, 32KB, 64KB, 128KB
        ram_ranges = [8192, 16384, 32768, 65536, 131072]

        entries = []
        for macs_limit in macs_ranges:
            for ram_limit in ram_ranges:
                # Skip if MACs and RAM are both too high (wasteful)
                # or both too low (unrealistic)
                if macs_limit > 100000 and ram_limit < 16384:
                    continue
                if macs_limit < 20000 and ram_limit > 65536:
                    continue

                # Limit number of entries to target
                if len(entries) >= num_entries:
                    break

                # Find a optimal network under these constraints
                config = {
                    "population_size": 30,
                    "generations": 30,
                    "early_stop": 10,
                    "max_layers": max_layers,
                    "input_shape": input_shape,
                    "num_classes": num_classes,
                }

                generator = ModelGenerator(estimator, config)
                structure = generator.generate_evolved()

                # Extract metrics from the best structure
                # We need to re-evaluate to get full metrics
                model_info = generator._structure_to_model_info(structure)
                result = estimator.estimate(model_info)

                entry = {
                    "signature": self._get_signature(structure),
                    "board": board,
                    "ram_kb": result.get("peak_ram", 0) / 1024.0,
                    "flash_kb": result.get("flash", 0) / 1024.0,
                    "latency_ms": result.get("latency_ms", 0),
                    "macs": result.get("macs", 0),
                    "params": result.get("params", 0),
                    "constraints": {
                        "max_macs": macs_limit,
                        "max_ram": ram_limit,
                    },
                    "op_sequence": structure.get("layers", []),
                    "input_shape": input_shape,
                    "output_shape": [1, num_classes],
                    "status": "verified",
                    "created_at": time.time(),
                    "updated_at": time.time(),
                    "test_count": 1,
                    "std_dev": {
                        "latency_ms": 0.0,
                        "ram_kb": 0.0,
                    }
                }
                entries.append(entry)

        self.entries = entries
        self._rebuild_index()

    def lookup(self, constraints: Dict[str, Any]) -> Dict[str, Any]:
        """
        Look up the best network for given constraints.

        Args:
            constraints: Dictionary with max_macs, max_ram, max_flash.

        Returns:
            ModelInfo dictionary of the best network.
        """
        max_macs = constraints.get("max_macs", 100000)
        max_ram = constraints.get("max_ram", 32768)
        max_flash = constraints.get("max_flash", 65536)

        # Find the best entry within constraints
        # Score = how well the entry fits the constraints (lower is better)
        # We want the one that uses the most resources (higher performance)
        # while staying within bounds.
        best_entry = None
        best_score = float("inf")

        for entry in self.entries:
            entry_macs = entry.get("macs", float("inf"))
            entry_ram = entry.get("ram_kb", float("inf")) * 1024
            entry_flash = entry.get("flash_kb", float("inf")) * 1024

            # Skip entries that exceed constraints
            if entry_macs > max_macs:
                continue
            if entry_ram > max_ram:
                continue
            if entry_flash > max_flash:
                continue

            # Score: lower is better. We want to be close to the limits
            # without exceeding them.
            score = (
                (max_macs - entry_macs) / max_macs * 0.4 +
                (max_ram - entry_ram) / max_ram * 0.3 +
                (max_flash - entry_flash) / max_flash * 0.3
            )

            if score < best_score:
                best_score = score
                best_entry = entry

        if best_entry is None:
            raise ValueError(
                f"No entry found for constraints: "
                f"max_macs={max_macs}, max_ram={max_ram}, "
                f"max_flash={max_flash}"
            )

        # Convert the entry to model_info
        return self._entry_to_model_info(best_entry)

    def _entry_to_model_info(self, entry: Dict[str, Any]) -> Dict[str, Any]:
        """
        Convert a table entry to model_info.

        Args:
            entry: Table entry.

        Returns:
            ModelInfo dictionary.
        """
        builder = ModelBuilder("ang_table_result")

        input_shape = entry.get("input_shape", [1, 28, 28, 1])
        num_classes = entry.get("output_shape", [1, 10])[1]

        # Add input
        input_idx = builder.add_input("input", input_shape, "int8")

        # Add layers
        current_idx = input_idx
        for layer in entry.get("op_sequence", []):
            layer_type = layer.get("type")

            if layer_type == "conv":
                kernel = layer.get("kernel", 3)
                channels = layer.get("channels", 16)
                stride = layer.get("stride", 1)

                # Create output tensor
                output_shape = list(input_shape)
                output_shape[3] = channels
                output_idx = builder.add_tensor(
                    f"conv_output", output_shape, "int8"
                )
                builder.add_conv(
                    current_idx, output_idx, kernel, channels, stride
                )
                current_idx = output_idx

            elif layer_type == "pool":
                kernel = layer.get("kernel", 2)
                stride = layer.get("stride", 2)

                # Create output tensor (shape halved)
                output_shape = list(input_shape)
                output_shape[1] = max(1, output_shape[1] // stride)
                output_shape[2] = max(1, output_shape[2] // stride)
                output_idx = builder.add_tensor(
                    f"pool_output", output_shape, "int8"
                )
                # Add pool operation
                # TODO: implement pool in builder
                current_idx = output_idx

            elif layer_type == "fc":
                units = layer.get("units", 64)
                output_idx = builder.add_tensor(
                    f"fc_output", [1, units], "int8"
                )
                builder.add_fc(current_idx, output_idx, units)
                current_idx = output_idx

        # Add final output
        output_idx = builder.add_output("output", [1, num_classes], "int8")
        if current_idx != output_idx:
            builder.add_fc(current_idx, output_idx, num_classes, "none")

        model_info = builder.build()
        return model_info.to_dict()

    def update_table(
        self,
        add_ops: Optional[List[str]] = None,
        recalibrate: bool = False,
        entries: Optional[List[str]] = None,
    ) -> None:
        """
        Update the table with new or recalibrated entries.

        Args:
            add_ops: List of operator types to add (e.g., ["dwconv"]).
            recalibrate: If True, recalibrate existing entries.
            entries: List of entry signatures to recalibrate (if None, all).
        """
        # TODO: Full implementation
        # This would need to:
        #   1. Generate probe networks for new operators
        #   2. Run them on hardware (via estimator)
        #   3. Add or update entries

        # For now, just mark metadata
        self.metadata["updated_at"] = time.time()

    def merge(self, other_table_path: str) -> None:
        """
        Merge another table into this one.

        Args:
            other_table_path: Path to the other table file.
        """
        other = TableManager(other_table_path)

        for entry in other.entries:
            signature = entry.get("signature", "")
            if signature in self._index:
                # Entry exists, skip (keep existing)
                continue
            # Add new entry
            self.entries.append(entry)

        self._rebuild_index()
        self.metadata["merged_at"] = time.time()

    def prune(
        self,
        older_than_days: int = 90,
        deprecated_only: bool = True,
    ) -> None:
        """
        Remove stale or deprecated entries from the table.

        Args:
            older_than_days: Remove entries older than this many days.
            deprecated_only: If True, only remove entries marked as deprecated.
        """
        current_time = time.time()
        max_age_seconds = older_than_days * 24 * 60 * 60

        new_entries = []
        for entry in self.entries:
            status = entry.get("status", "verified")

            if status == "deprecated" and deprecated_only:
                continue

            created_at = entry.get("created_at", 0)
            if current_time - created_at > max_age_seconds:
                continue

            new_entries.append(entry)

        self.entries = new_entries
        self._rebuild_index()

    def get_stats(self) -> Dict[str, Any]:
        """
        Get statistics about the table.

        Returns:
            Dictionary with statistics.
        """
        if not self.entries:
            return {"total_entries": 0}

        macs_values = [e.get("macs", 0) for e in self.entries]
        ram_values = [e.get("ram_kb", 0) for e in self.entries]
        flash_values = [e.get("flash_kb", 0) for e in self.entries]
        latency_values = [e.get("latency_ms", 0) for e in self.entries]

        return {
            "total_entries": len(self.entries),
            "macs": {
                "min": min(macs_values),
                "max": max(macs_values),
                "avg": sum(macs_values) / len(macs_values),
            },
            "ram_kb": {
                "min": min(ram_values),
                "max": max(ram_values),
                "avg": sum(ram_values) / len(ram_values),
            },
            "flash_kb": {
                "min": min(flash_values),
                "max": max(flash_values),
                "avg": sum(flash_values) / len(flash_values),
            },
            "latency_ms": {
                "min": min(latency_values),
                "max": max(latency_values),
                "avg": sum(latency_values) / len(latency_values),
            },
            "metadata": self.metadata,
        }

    def find_best_for_constraints(
        self,
        max_macs: int,
        max_ram_kb: int,
        max_flash_kb: int,
    ) -> Optional[Dict[str, Any]]:
        """
        Find the best entry for given constraints (lower-level API).

        Args:
            max_macs: Maximum MACs.
            max_ram_kb: Maximum RAM in KB.
            max_flash_kb: Maximum Flash in KB.

        Returns:
            The best matching entry, or None if none found.
        """
        constraints = {
            "max_macs": max_macs,
            "max_ram": max_ram_kb * 1024,
            "max_flash": max_flash_kb * 1024,
        }
        return self.lookup(constraints)


# ============================================================================
# Example vendor script for hardware evaluation
# ============================================================================

VENDOR_ESTIMATOR_TEMPLATE = '''
# vendor_estimator.py
# Vendor-specific hardware estimator for ANG.
#
# This script is called by ANG when --estimator hardware is used.
# It must implement the estimate() function.

import subprocess
import json
from typing import Dict, Any


def estimate(model_info: Dict[str, Any]) -> Dict[str, Any]:
    """
    Estimate model performance on target hardware.

    Args:
        model_info: ModelInfo dictionary.

    Returns:
        Dictionary with:
            - score: float (higher is better)
            - macs: int
            - params: int
            - peak_ram: int (bytes)
            - flash: int (bytes)
            - latency_ms: float (optional)
    """
    # 1. Generate C code (call TinyMLC)
    # 2. Compile with vendor toolchain
    # 3. Flash and run on hardware
    # 4. Measure latency, RAM, Flash usage
    # 5. Return results

    # Example implementation (replace with actual hardware test):
    macs = sum_layer_macs(model_info)
    params = count_params(model_info)
    ram = measure_peak_ram(model_info)
    flash = measure_flash_size(model_info)

    # Run on hardware (this is where the real work happens)
    latency = run_hardware_inference(model_info)

    # Score: accuracy proxy / latency
    # Higher score = better
    accuracy_proxy = 0.8  # Simplified
    score = accuracy_proxy / (latency + 1.0)

    return {
        "score": score * 100.0,
        "macs": macs,
        "params": params,
        "peak_ram": ram,
        "flash": flash,
        "latency_ms": latency,
        "details": {
            "board": "STM32F407",
            "clock_mhz": 168,
            "temperature": 25.0,
        }
    }


# ========== Helper functions (vendor implements these) ==========

def sum_layer_macs(model_info):
    """Calculate MACs from model_info."""
    from utils import calculate_macs
    return calculate_macs(model_info)

def count_params(model_info):
    """Count parameters from model_info."""
    from utils import calculate_params
    return calculate_params(model_info)

def measure_peak_ram(model_info):
    """Measure peak RAM usage on hardware."""
    # Vendor implementation
    return 32768

def measure_flash_size(model_info):
    """Measure Flash usage on hardware."""
    # Vendor implementation
    return 65536

def run_hardware_inference(model_info):
    """Run inference on hardware and measure latency."""
    # Vendor implementation
    return 1.2
'''
