// Auto-generated code, do not modify manually
// Generated by tinymlc

#ifndef TINYMLC_MODEL_H
#define TINYMLC_MODEL_H

#include <stdint.h>

#define INPUT_SIZE 784
#define OUTPUT_SIZE 10


#define INPUT_SIZE_1 784





// LSTM right shift bits (calculated from model quantization parameters)
#define LSTM_SHIFT_I 8
#define LSTM_SHIFT_F 8
#define LSTM_SHIFT_G 8
#define LSTM_SHIFT_O 8

// Inference function declaration

    void tinymlc_inference(const int8_t* input, int8_t* output);


#endif // TINYMLC_MODEL_H