// Auto-generated code, do not modify manually
// Generated by tinymlc

#include "tinymlc.h"
#include "fc_weights.h"
#include "conv_weights.h"
#include "model.h"
#include "debug_print.h"
#include <stddef.h>

// Input/output sizes
#define INPUT_SIZE 784
#define OUTPUT_SIZE 10

// Intermediate tensor memory (static allocation, placed outside function)


int8_t tensor_1[12544] __attribute__((section(".bss")));



int8_t tensor_4[6272] __attribute__((section(".bss")));



int8_t tensor_7[50176] __attribute__((section(".bss")));



int8_t tensor_10[12544] __attribute__((section(".bss")));



int8_t tensor_13[12544] __attribute__((section(".bss")));



int8_t tensor_16[6272] __attribute__((section(".bss")));



int8_t tensor_19[25088] __attribute__((section(".bss")));



int8_t tensor_22[50176] __attribute__((section(".bss")));



int8_t tensor_25[6272] __attribute__((section(".bss")));



int8_t tensor_28[32] __attribute__((section(".bss")));



int8_t tensor_31[10] __attribute__((section(".bss")));





// Inference function

void tinymlc_inference(const int8_t* input, int8_t* output) {
    // Input tensor mapping
    int8_t* tensor_0 = (int8_t*)input;

    // Execute operators in order
    
        
        tmlc_conv2d_s8(
            tensor_0,
            conv_weights,
            conv_bias,
            tensor_1,
            28,
            28,
            1,
            24,
            24,
            16,
            5,
            5,
            1,
            1,
            0,
            0,
            8388608,
            0
        );
        
    
        
        tmlc_conv2d_s8(
            tensor_1,
            conv_weights,
            conv_bias,
            tensor_4,
            28,
            28,
            16,
            24,
            24,
            8,
            5,
            5,
            1,
            1,
            0,
            0,
            8388608,
            0
        );
        
    
        
        tmlc_conv2d_s8(
            tensor_4,
            conv_weights,
            conv_bias,
            tensor_7,
            28,
            28,
            8,
            28,
            28,
            64,
            1,
            1,
            1,
            1,
            0,
            0,
            8388608,
            0
        );
        
    
        
        tmlc_conv2d_s8(
            tensor_7,
            conv_weights,
            conv_bias,
            tensor_10,
            28,
            28,
            64,
            28,
            28,
            16,
            1,
            1,
            1,
            1,
            0,
            0,
            8388608,
            0
        );
        
    
        
        tmlc_conv2d_s8(
            tensor_10,
            conv_weights,
            conv_bias,
            tensor_13,
            28,
            28,
            16,
            28,
            28,
            16,
            1,
            1,
            1,
            1,
            0,
            0,
            8388608,
            0
        );
        
    
        
        tmlc_conv2d_s8(
            tensor_13,
            conv_weights,
            conv_bias,
            tensor_16,
            28,
            28,
            16,
            14,
            14,
            8,
            1,
            1,
            2,
            2,
            0,
            0,
            8388608,
            0
        );
        
    
        
        tmlc_conv2d_s8(
            tensor_16,
            conv_weights,
            conv_bias,
            tensor_19,
            28,
            28,
            8,
            12,
            12,
            32,
            5,
            5,
            2,
            2,
            0,
            0,
            8388608,
            0
        );
        
    
        
        tmlc_conv2d_s8(
            tensor_19,
            conv_weights,
            conv_bias,
            tensor_22,
            28,
            28,
            32,
            24,
            24,
            64,
            5,
            5,
            1,
            1,
            0,
            0,
            8388608,
            0
        );
        
    
        
        tmlc_conv2d_s8(
            tensor_22,
            conv_weights,
            conv_bias,
            tensor_25,
            28,
            28,
            64,
            26,
            26,
            8,
            3,
            3,
            1,
            1,
            0,
            0,
            8388608,
            0
        );
        
    
        
        tmlc_fully_connected_s8(
            tensor_25,
            fc_weights,
            fc_bias,
            tensor_28,
            6272,
            32,
            8388608,
            0
        );
        
    
        
        tmlc_fully_connected_s8(
            tensor_28,
            fc_weights,
            fc_bias,
            tensor_31,
            32,
            10,
            8388608,
            0
        );
        
    

    // Output tensor mapping
    if (output != NULL) {
        for (int i = 0; i < OUTPUT_SIZE; i++) {
            output[i] = tensor_31[i];
        }
    }
}